spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: filmland
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format-sql: true
api:
  key: ${API_KEY}

